services:

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data

  worker:
    build: .
    volumes:
      - ./:/app
      - ./java_repo:/app/java_repo
      - ./cache:/app/cache
    depends_on:
      - redis
      - qdrant
    env_file:
      - .env

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus

  webhook:
    build: .
    command: python services/github_webhook.py
    ports:
      - "5001:5000"
    env_file:
      - .env
    environment:
    - PYTHONPATH=/app   # ✅ ADD THIS
    depends_on:
      - worker


volumes:
  qdrant_data:
  redis_data:
  prometheus_data: